# Generated by Django 3.2.4 on 2021-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0004_auto_20210616_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
